### ISSUE TITLE
Raise NoMethodError in case of absence of ActionMailer.

### ISSUE THREAD

**Issue by zekefast** [tubbo/activejob-scheduler#3]
# Steps to reproduce
1. Comment in `config/application.rb` `require "action_mailer/railtie"`.
2. Run `rails generate activejob:schedule`

# Actual results
```
/home/zekefast/.rvm/gems/ruby-2.2.2@icon_peak_-_dashboard/gems/railties-4.2.1/lib/rails/railtie/configuration.rb:95:in `method_missing': undefined method `action_mailer' for #<Rails::Application::Configuration:0x00000003f1b460> (NoMethodError)
	from /home/zekefast/development/project/job/brightgrove/icon_peak/dashboard/backend/config/environments/development.rb:17:in `block in <top (required)>'
	from /home/zekefast/.rvm/gems/ruby-2.2.2@icon_peak_-_dashboard/gems/railties-4.2.1/lib/rails/railtie.rb:210:in `instance_eval'
	from /home/zekefast/.rvm/gems/ruby-2.2.2@icon_peak_-_dashboard/gems/railties-4.2.1/lib/rails/railtie.rb:210:in `configure'
	from /home/zekefast/development/project/job/brightgrove/icon_peak/dashboard/backend/config/environments/development.rb:1:in `<top (required)>'
	from /home/zekefast/.rvm/gems/ruby-2.2.2@icon_peak_-_dashboard/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
	from /home/zekefast/.rvm/gems/ruby-2.2.2@icon_peak_-_dashboard/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/zekefast/.rvm/gems/ruby-2.2.2@icon_peak_-_dashboard/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/zekefast/.rvm/gems/ruby-2.2.2@icon_peak_-_dashboard/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
	from /home/zekefast/.rvm/gems/ruby-2.2.2@icon_peak_-_dashboard/gems/railties-4.2.1/lib/rails/engine.rb:598:in `block (2 levels) in <class:Engine>'
	from /home/zekefast/.rvm/gems/ruby-2.2.2@icon_peak_-_dashboard/gems/railties-4.2.1/lib/rails/engine.rb:597:in `each'
	from /home/zekefast/.rvm/gems/ruby-2.2.2@icon_peak_-_dashboard/gems/railties-4.2.1/lib/rails/engine.rb:597:in `block in <class:Engine>'
	from /home/zekefast/.rvm/gems/ruby-2.2.2@icon_peak_-_dashboard/gems/railties-4.2.1/lib/rails/initializable.rb:30:in `instance_exec'
	from /home/zekefast/.rvm/gems/ruby-2.2.2@icon_peak_-_dashboard/gems/railties-4.2.1/lib/rails/initializable.rb:30:in `run'
	from /home/zekefast/.rvm/gems/ruby-2.2.2@icon_peak_-_dashboard/gems/railties-4.2.1/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /home/zekefast/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
	from /home/zekefast/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
	from /home/zekefast/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:420:in `block (2 levels) in each_strongly_connected_component_from'
	from /home/zekefast/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
	from /home/zekefast/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:419:in `block in each_strongly_connected_component_from'
	from /home/zekefast/.rvm/gems/ruby-2.2.2@icon_peak_-_dashboard/gems/railties-4.2.1/lib/rails/initializable.rb:44:in `each'
	from /home/zekefast/.rvm/gems/ruby-2.2.2@icon_peak_-_dashboard/gems/railties-4.2.1/lib/rails/initializable.rb:44:in `tsort_each_child'
	from /home/zekefast/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:413:in `call'
	from /home/zekefast/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:413:in `each_strongly_connected_component_from'
	from /home/zekefast/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
	from /home/zekefast/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:345:in `each'
	from /home/zekefast/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:345:in `call'
	from /home/zekefast/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
	from /home/zekefast/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
	from /home/zekefast/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
	from /home/zekefast/.rvm/gems/ruby-2.2.2@icon_peak_-_dashboard/gems/railties-4.2.1/lib/rails/initializable.rb:54:in `run_initializers'
	from /home/zekefast/.rvm/gems/ruby-2.2.2@icon_peak_-_dashboard/gems/railties-4.2.1/lib/rails/application.rb:352:in `initialize!'
	from /home/zekefast/development/project/job/brightgrove/icon_peak/dashboard/backend/config/environment.rb:5:in `<top (required)>'
	from /home/zekefast/.rvm/gems/ruby-2.2.2@icon_peak_-_dashboard/gems/railties-4.2.1/lib/rails/application.rb:328:in `require'
	from /home/zekefast/.rvm/gems/ruby-2.2.2@icon_peak_-_dashboard/gems/railties-4.2.1/lib/rails/application.rb:328:in `require_environment!'
	from /home/zekefast/.rvm/gems/ruby-2.2.2@icon_peak_-_dashboard/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:142:in `require_application_and_environment!'
	from /home/zekefast/.rvm/gems/ruby-2.2.2@icon_peak_-_dashboard/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:128:in `generate_or_destroy'
	from /home/zekefast/.rvm/gems/ruby-2.2.2@icon_peak_-_dashboard/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:50:in `generate'
	from /home/zekefast/.rvm/gems/ruby-2.2.2@icon_peak_-_dashboard/gems/railties-4.2.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /home/zekefast/.rvm/gems/ruby-2.2.2@icon_peak_-_dashboard/gems/railties-4.2.1/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

# Expected results
* Degrade gracefully in case of absence of Rails components.

**Comment by tubbo** [comment]
ActiveJob::Scheduler doesn't use ActionMailer at all, this has to do with your Rails configuration in `config/development.rb`. When you exclude components of Rails, you have to go through your configuration and comment out or remove the settings pertaining to those files. Same thing if you removed Sprockets or ActionController, except you'd hit a different line for the same error.

**Comment by zekefast** [comment]
Thanks.

**Comment by tubbo** [comment]
Sorry it took so long! :)


- T
